import 'package:get/get.dart';
import 'package:flutter/material.dart';

class MyTripsController extends GetxController {
  final selectedTab = 0.obs;
  final selectedTrip = Rxn<Map<String, dynamic>>();

  final trips = <Map<String, dynamic>>[
    // Today Trip
    {
      'title': 'Dubai Business Trip',
      'location': 'Dubai, UAE',
      'dates': '12-17 Dec 2025',
      'detailedDates': '12-17 Dec 2025 • 5 days',
      'image': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400',
      'services': ['Flight', 'Hotel', 'Tour'],
      'travelers': 2,
      'status': 'Today',
      'tag': 'Visit Adventure',
      'bookingId': 'TB-294830',
      'bookedOn': '25 Nov 2025',
      'travelerName': 'Mandula Hoosen',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$1,250',
      'cancellationPolicy': 'Free cancellation till 05 Dec 2025',
      'bookings': [
        {
          'type': 'Flight',
          'title': 'Lagos → Tokyo',
          'subtitle': 'Round trip',
          'time': '09 Jan, 10:30 - 21:45',
          'extra': 'Airline: Emirates, Flight: JK-763',
          'tags': ['Economy', '2 bags', 'Seat: 14A'],
          'image': 'https://images.stockcake.com/public/f/b/6/fb6acf1b-fcaa-4152-b48b-6b0e2b0c5374_large/airplane-mid-flight-stockcake.jpg',
          'icon': Icons.flight_takeoff,
        },
        {
          'type': 'Hotel',
          'title': 'Shinbay Sokuro Hotel',
          'subtitle': '',
          'time': 'Check-in: 05 Jan • Check-out: 08 Jan',
          'extra': 'Room: Deluxe Double • Breakfast included',
          'tags': ['2 Guests'],
          'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=200',
          'icon': Icons.hotel,
        },
        {
          'type': 'Tour',
          'title': 'Tokyo Cherry Blossom Tour',
          'subtitle': '',
          'details': [
            'Start: 06 Jan, 09:00',
            'Duration: 8 hours',
            'Language: English, Japanese',
            'Group size: up to 12 people'
          ],
          'tags': ['Guided', 'Family Friendly', 'Includes lunch'],
          'icon': Icons.directions_bus,
        },
      ],
    },

    // Today Trips
    {
      'title': 'Miami Beach Hotel',
      'location': 'Miami, USA',
      'dates': '14 Jan 2026',
      'detailedDates': '14-16 Jan 2026 • 3 days',
      'image': 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400',
      'services': ['Hotel'],
      'travelers': 2,
      'status': 'Today',
      'tag': 'Beach Vacation',
      'bookingId': 'TB-294835',
      'bookedOn': '01 Jan 2026',
      'travelerName': 'Sarah Miller',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$680',
      'cancellationPolicy': 'Free cancellation till 12 Jan 2026',
      'bookings': [
        {
          'type': 'Hotel',
          'title': 'Ocean View Resort Miami',
          'subtitle': '',
          'time': 'Check-in: 14 Jan • Check-out: 16 Jan',
          'extra': 'Room: Ocean View Suite • Breakfast included',
          'tags': ['2 Guests', 'Beach Access', 'Pool'],
          'image': 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400',
          'icon': Icons.hotel,
        },
      ],
    },
    {
      'title': 'Rome City Tour',
      'location': 'Rome, Italy',
      'dates': '14 Jan 2026',
      'detailedDates': '14 Jan 2026 • 1 day',
      'image': 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400',
      'services': ['Tour'],
      'travelers': 4,
      'status': 'Today',
      'tag': 'Cultural Trip',
      'bookingId': 'TB-294836',
      'bookedOn': '05 Jan 2026',
      'travelerName': 'Mike Johnson',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$320',
      'cancellationPolicy': 'No cancellation allowed',
      'bookings': [
        {
          'type': 'Tour',
          'title': 'Ancient Rome Walking Tour',
          'subtitle': '',
          'details': [
            'Start: 14 Jan, 09:00',
            'Duration: 6 hours',
            'Language: English, Italian',
            'Group size: up to 15 people'
          ],
          'tags': ['Guided', 'Historical Sites', 'Includes lunch'],
          'icon': Icons.directions_bus,
        },
      ],
    },
    {
      'title': 'Los Angeles → New York',
      'location': 'New York, USA',
      'dates': '14 Jan 2026',
      'image': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=400',
      'services': ['Flight'],
      'travelers': 1,
      'status': 'Today',
      'tag': 'Business Travel',
      'bookingId': 'TB-294837',
      'bookedOn': '28 Dec 2025',
      'travelerName': 'Emma Davis',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$450',
      'cancellationPolicy': 'Free cancellation till 10 Jan 2026',
      'bookings': [
        {
          'type': 'Flight',
          'title': 'Los Angeles → New York',
          'subtitle': 'One way',
          'time': '14 Jan, 08:00 - 16:30',
          'extra': 'Airline: American Airlines, Flight: AA-125',
          'tags': ['Business Class', '1 bag', 'Seat: 3A'],
          'image': 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400',
          'icon': Icons.flight_takeoff,
        },
      ],
    },
    {
      'title': 'Downtown Car Rental',
      'location': 'Seattle, USA',
      'dates': 'Pickup 14 Jan • 5 days',
      'image': 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=400',
      'services': ['Car'],
      'travelers': 2,
      'status': 'Today',
      'tag': 'Road Trip',
      'bookingId': 'TB-294838',
      'bookedOn': '02 Jan 2026',
      'travelerName': 'David Wilson',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$380',
      'cancellationPolicy': 'Free cancellation till 13 Jan 2026',
      'bookings': [
        {
          'type': 'Car',
          'title': 'Toyota Camry 2024',
          'subtitle': '',
          'time': 'Pickup: 14 Jan, 10:00 • Return: 19 Jan, 10:00',
          'extra': 'Rental Company: Enterprise • Location: Downtown Seattle',
          'tags': ['Automatic', 'Full Insurance', 'GPS Included'],
          'image': 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=400',
          'icon': Icons.directions_car,
        },
      ],
    },

    // Upcoming Trips
    {
      'title': 'Tokyo Cherry Tour',
      'fullTitle': 'Tokyo Cherry Blossom Tour',
      'location': 'Tokyo, Japan',
      'dates': '5-8 Jun 2026',
      'detailedDates': '5-8 Jan 2026 • 4 days',
      'image': 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400',
      'services': ['Hotel'],
      'travelers': 3,
      'status': 'Upcoming',
      'bookingId': 'TB-294830',
      'bookedOn': '25 Nov 2025',
      'travelerName': 'Mandula Hoosen',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$1,250',
      'cancellationPolicy': 'Free cancellation till 30 Dec 2025',
      'bookings': [
        {
          'type': 'Hotel',
          'title': 'Tokyo Grand Hotel',
          'subtitle': '',
          'time': 'Check-in: 05 Jan • Check-out: 08 Jan',
          'extra': 'Room: Deluxe Twin • Breakfast included',
          'tags': ['3 Guests', 'City View'],
          'image': 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400',
          'icon': Icons.hotel,
        },
      ],
    },
    {
      'title': 'Lagos → London',
      'location': 'London, UK',
      'dates': '5-8 Jun 2026',
      'image': 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400',
      'services': ['Flight'],
      'travelers': 3,
      'status': 'Upcoming',
      'bookingId': 'TB-294831',
      'bookedOn': '20 Nov 2025',
      'travelerName': 'John Smith',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$850',
      'cancellationPolicy': 'Free cancellation till 01 Dec 2025',
      'bookings': [
        {
          'type': 'Flight',
          'title': 'Lagos → London',
          'subtitle': 'Round trip',
          'time': '05 Jun, 14:00 - 20:30',
          'extra': 'Airline: British Airways, Flight: BA-456',
          'tags': ['Economy', '2 bags', 'Seats: 12A, 12B, 12C'],
          'image': 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400',
          'icon': Icons.flight_takeoff,
        },
      ],
    },
    {
      'title': 'Airport Pickup Car Rental',
      'location': 'New York, USA',
      'dates': 'Pickup 17 Dec • 3 days',
      'image': 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400',
      'services': ['Car'],
      'travelers': 3,
      'status': 'Upcoming',
      'bookingId': 'TB-294832',
      'bookedOn': '18 Nov 2025',
      'travelerName': 'Sarah Johnson',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$450',
      'cancellationPolicy': 'Free cancellation till 10 Dec 2025',
      'bookings': [
        {
          'type': 'Car',
          'title': 'Honda CR-V 2024',
          'subtitle': '',
          'time': 'Pickup: 17 Dec, 15:00 • Return: 20 Dec, 15:00',
          'extra': 'Rental Company: Hertz • Location: JFK Airport',
          'tags': ['Automatic', 'SUV', '5 Seats'],
          'image': 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400',
          'icon': Icons.directions_car,
        },
      ],
    },
    {
      'title': 'Bali Island Adventure',
      'location': 'Bali, Indonesia',
      'dates': '20-25 Feb 2026',
      'detailedDates': '20-25 Feb 2026 • 6 days',
      'image': 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400',
      'services': ['Tour'],
      'travelers': 5,
      'status': 'Upcoming',
      'bookingId': 'TB-294839',
      'bookedOn': '10 Jan 2026',
      'travelerName': 'Linda Martinez',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$1,850',
      'cancellationPolicy': 'Free cancellation till 15 Feb 2026',
      'bookings': [
        {
          'type': 'Tour',
          'title': 'Bali Complete Island Tour',
          'subtitle': '',
          'details': [
            'Start: 20 Feb, 08:00',
            'Duration: 6 days',
            'Language: English, Indonesian',
            'Group size: up to 20 people'
          ],
          'tags': ['Guided', 'All Meals Included', 'Beach Activities'],
          'icon': Icons.directions_bus,
        },
      ],
    },
    {
      'title': 'Sydney Opera House Tour',
      'location': 'Sydney, Australia',
      'dates': '10-12 Mar 2026',
      'image': 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=400',
      'services': ['Tour'],
      'travelers': 2,
      'status': 'Upcoming',
      'bookingId': 'TB-294840',
      'bookedOn': '08 Jan 2026',
      'travelerName': 'Chris Anderson',
      'paymentStatus': 'Partial payment',
      'totalAmount': '\$950',
      'cancellationPolicy': 'Free cancellation till 05 Mar 2026',
      'bookings': [
        {
          'type': 'Tour',
          'title': 'Sydney Highlights Tour',
          'subtitle': '',
          'details': [
            'Start: 10 Mar, 10:00',
            'Duration: 3 days',
            'Language: English',
            'Group size: up to 10 people'
          ],
          'tags': ['Opera House', 'Harbour Bridge', 'Includes Lunch'],
          'icon': Icons.directions_bus,
        },
      ],
    },
    {
      'title': 'Swiss Alps Ski Trip',
      'location': 'Zurich, Switzerland',
      'dates': '15-22 Feb 2026',
      'image': 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=400',
      'services': ['Tour'],
      'travelers': 6,
      'status': 'Upcoming',
      'bookingId': 'TB-294841',
      'bookedOn': '12 Jan 2026',
      'travelerName': 'Jessica Brown',
      'paymentStatus': 'Paid full',
      'totalAmount': '\$3,200',
      'cancellationPolicy': 'Free cancellation till 10 Feb 2026',
      'bookings': [
        {
          'type': 'Tour',
          'title': 'Swiss Alps Skiing Adventure',
          'subtitle': '',
          'details': [
            'Start: 15 Feb, 07:00',
            'Duration: 8 days',
            'Language: English, German',
            'Group size: up to 25 people'
          ],
          'tags': ['Ski Equipment Included', 'All Meals', 'Instructor Available'],
          'icon': Icons.directions_bus,
        },
      ],
    },

    // Canceled Trips - Each with only ONE service
    {
      'title': 'Paris Flight Booking',
      'location': 'Paris, France',
      'dates': '20-25 Nov 2025',
      'detailedDates': '20-25 Nov 2025 • 6 days',
      'image': 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400',
      'services': ['Flight'],
      'travelers': 2,
      'status': 'Canceled',
      'bookingId': 'TB-284920',
      'bookedOn': '10 Oct 2025',
      'canceledOn': '15 Nov 2025',
      'travelerName': 'Robert Davis',
      'paymentStatus': 'Refunded',
      'refundAmount': '\$2,100',
      'totalAmount': '\$2,100',
      'cancellationReason': 'Changed travel plans',
      'cancellationPolicy': 'Full refund issued',
    },
    {
      'title': 'Singapore Hotel Reservation',
      'location': 'Singapore',
      'dates': '10-15 Dec 2025',
      'image': 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400',
      'services': ['Hotel'],
      'travelers': 4,
      'status': 'Canceled',
      'bookingId': 'TB-279845',
      'bookedOn': '05 Sep 2025',
      'canceledOn': '10 Nov 2025',
      'travelerName': 'Emma Wilson',
      'paymentStatus': 'Partially Refunded',
      'refundAmount': '\$850',
      'totalAmount': '\$1,200',
      'cancellationReason': 'Medical emergency',
      'cancellationPolicy': 'Cancellation fee: \$350',
    },
    {
      'title': 'Maldives City Tour',
      'location': 'Maldives',
      'dates': '1-7 Jan 2026',
      'detailedDates': '1-7 Jan 2026 • 7 days',
      'image': 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=400',
      'services': ['Tour'],
      'travelers': 2,
      'status': 'Canceled',
      'bookingId': 'TB-265432',
      'bookedOn': '20 Aug 2025',
      'canceledOn': '05 Nov 2025',
      'travelerName': 'Michael Brown',
      'paymentStatus': 'No Refund',
      'refundAmount': '\$0',
      'totalAmount': '\$3,500',
      'cancellationReason': 'Non-refundable booking',
      'cancellationPolicy': 'No refund - Late cancellation',
    },
    {
      'title': 'Barcelona Car Rental',
      'location': 'Barcelona, Spain',
      'dates': '15-20 Oct 2025',
      'image': 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=400',
      'services': ['Car'],
      'travelers': 3,
      'status': 'Canceled',
      'bookingId': 'TB-258721',
      'bookedOn': '01 Jul 2025',
      'canceledOn': '25 Oct 2025',
      'travelerName': 'Lisa Anderson',
      'paymentStatus': 'Refunded',
      'refundAmount': '\$1,450',
      'totalAmount': '\$1,450',
      'cancellationReason': 'Flight schedule changed',
      'cancellationPolicy': 'Full refund within 24 hours',
    },
  ].obs;

  // Filtered trips based on selected tab
  List<Map<String, dynamic>> get filteredTrips {
    switch (selectedTab.value) {
      case 0: // All
        return trips;
      case 1: // Today
        return trips.where((trip) => trip['status'] == 'Today').toList();
      case 2: // Upcoming
        return trips.where((trip) => trip['status'] == 'Upcoming').toList();
      case 3: // Cancel
        return trips.where((trip) => trip['status'] == 'Canceled').toList();
      default:
        return trips;
    }
  }

  void selectTrip(Map<String, dynamic> trip) => selectedTrip.value = trip;
  void changeTab(int index) => selectedTab.value = index;
}